# Site settings
title: UNISA LUG
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Sito dell'UNISA LUG - Website of the UNISA LUG
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://d1nuc0m.github.io/unisa-lug.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

#Theme settings
lang: it_IT
header_pages:
  - index.markdown
  - agenda.markdown
  - community.markdown
  - direttivo-EWG.markdown
  - learning-resources.markdown
  - progetti.markdown
style: light
listen_for_clients_preferred_style: true
footer: 'UNISA LUG Website - Made with  <a href="https://jekyllrb.com/">Jekyll</a> and <a href="https://github.com/b2a3e8/jekyll-theme-console">jekyll-theme-console</a>'

# Build settings
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
