---
:page-liquid:
title: Home
description: Unisa LUG - Home
lang: it_IT
layout: page
permalink: /
---

= Home
Benvenuti sul sito dell'UNISA LUG - UNISA Libreware User Group!

_A scanso di equivoci: l'UNISA nel nome non vuol dire che siamo affiliati/appoggiati dall'università nè la rappresentiamo. Vedere sotto per ulteriori chiarimenti_

---

== FAQ
In stile software preferiamo presentarci con delle FAQ ;)


=== Chi siamo?

Siamo un gruppo di studenti dell'Università degli Studi di Salerno, interessati all'informatica ed in particolare ad hardware/software liberi.
Il gruppo nasce il 19 marzo 2020, nel pieno della quarantena, come punto di aggregazione virtuale su con un gruppo Telegram.
Attualmente ci "riuniamo" online, ma vorremmo costituirci come associazione studentesca non politica (alias non partecipante ad elezioni).

++++
<hr style="border: 0.5px solid grey; width:50%; margin-left: 0;">
++++

=== Cos'è un LUG?
LUG canonicamente sta per *Linux User Group*, quindi un gruppo di persone che utilizzano sistemi operativi Linux.
In maniera più estesa si parla di *Libreware User Group, un punto di aggregazione per persone interessate alla tecnologia ed all'informatica* (di solito soprattutto ad hardware/software libero).

++++
<hr style="border: 0.5px solid grey; width:50%; margin-left: 0;">
++++

=== Ma quindi è solo per esperti/smanettoni?
*No, anzi.* I LUG nascono proprio come punto di incontro tra chi è più esperto e chi ha voglia di imparare e per fare da punto di aggregazione per persone con un interesse comune.
Non sono richieste esperienze precedenti od altro, basta essere interessati all'informatica (meglio se ad hardware/software libero).
Per fare un paragone per iscriversi ad un circolo di scacchi di solito basta voler imparare, non è necessario essere Kasparov (e se vi chiedessero di esserlo, meglio cambiare circolo).

++++
<hr style="border: 0.5px solid grey; width:50%; margin-left: 0;">
++++

=== Ok, ma cosa sono hardware/software liberi?
*Hardware e software sono detti liberi se garantiscono delle libertà agli utilizzatori*:

. Libertà di utilizzo
. Libertà di modifica
. Libertà di ridistribuzione della versione originale
. Libertà di distribuzione di versioni modificate

Queste libertà non sono da sottovalutare, spiegarlo richiede ben più di una FAQ, per approfondimenti vedere https://www.gnu.org/philosophy/free-sw.html.en[la definizione della FSF di sofware libero] e https://www.gnu.org/philosophy/free-hardware-designs.html[la definizione della FSF di hardware libero].

++++
<hr style="border: 0.5px solid grey; width:50%; margin-left: 0;">
++++

=== Perché UNISA LUG come nome?
Semplicemente *siamo un LUG e siamo soprattutto studenti dell'UNISA*. Non vuol dire che sia un'iniziativa dell'università.

++++
<hr style="border: 0.5px solid grey; width:50%; margin-left: 0;">
++++

=== Conoscevo l'HCSS LUG, che ne è stato?
L'HCSS LUG (Hippocratica Civitas Studium Salerni LUG) è stato un LUG attivo presso l'Università degli Studi di Salerno negli anni scorsi.
Anche per ragioni anagrafiche non abbiamo alcun legame con quel progetto, pur essendo stata un'iniziativa interessante.